### ISSUE TITLE
Add instructions on how to require role assignment

### ISSUE THREAD

**Issue by gregjhogan** [Azure-Samples/active-directory-dotnet-daemon#10]
In the current instructions, it says to add a delegating permission.  This does nothing!  If you follow this example, ANY client ID in your tenant can make calls to the API ... extremely insecure.

Please add instructions on how to properly secure an API by turning on requiring role assignment:
![image](https://cloud.githubusercontent.com/assets/4112046/15034308/d0b271d2-1239-11e6-83cd-730801970621.png)

add a role to the service through the manifest:

``` javascript
  "appRoles": [
    {
      "allowedMemberTypes": [ "Application" ],
      "description": "Allow the application to access TodoListService",
      "displayName": "Access TodoListService",
      "id": "0C65E07C-9D03-4617-83D3-09ADAE44C4E1",
      "isEnabled": true,
      "origin": "Application",
      "value": "api-access"
    }
  ],
```

and assign that role to the daemon:
![image](https://cloud.githubusercontent.com/assets/4112046/15034316/e408d9d8-1239-11e6-8d19-dee94fe8239e.png)

**Comment by sergsalo** [comment]
I am trying to add this "require role assignment" in new portal, but it doesn't work. I'm getting error message when daemon app is trying to obtain token: "AADSTS50105: Application 'xxxxx-026e-4668-9da1-xxxxxx' is not assigned to a role for the application 'https://xxxxx.onmicrosoft.com/xxxxxx-10aa-441f-92b2-xxxxxxxxxxx'.
Trace ID: 4f0a1a2d-0dba-4fd2-993e-d17bc97c4400
Correlation ID: b28f2644-60a1-41ca-8aef-16bd5f5d526b
Timestamp: 2017-07-10 23:28:24Z"

**Comment by sergsalo** [comment]
I needed admin consent for the daemon app for this to work

**Comment by jmprieur** [comment]
Done in the new Readme.md
