### ISSUE TITLE
Are AppKeys deprecated?

### ISSUE THREAD

**Issue by EricDAllen** [Azure-Samples/active-directory-dotnet-daemon#11]
The documentation on the main Code screen says:
Step 3: Register the sample with your Azure Active Directory tenant
Header: Register the TodoListDaemon app
11. Create a new key for the application. Save the configuration so you can view the key value. Save this aside for when you configure the project in Visual Studio.

I'm not seeing anywhere on my Azure "Configure" screen where generating (or viewing) a key is possible.  My tenant comes from Office 365, in case that helps.

BTW - My goal (stymied so far) is simply to write a background service that pushes contacts from my system into a contact folder my customer will see in Outlook.  I would really appreciate a heads-up if this sample project is NOT expected to handle the authentication needed for that scenario.

**Comment by jmprieur** [comment]
Readme was updated.
