### ISSUE TITLE
Failed to Configure Permissions forDaemon app

### ISSUE THREAD

**Issue by yuronhe** [Azure-Samples/active-directory-dotnet-daemon#13]
Step 3: 
8. Configure Permissions for your application - in the Settings menu, choose the 'Required permissions' section, click on Add, then Select an API, and type 'TodoListService' in the textbox. Then, click on Select Permissions and select 'Access TodoListService'.

From the following Portal, can't find 'TodoListService' app. After  type 'TodoListService' in the textbox, Got "No result". So can't continue.

**Comment by ruffzy** [comment]
I have the exact same issue. My own apps don't show up in this list. Not on the new portal and also not on the old one.

**Comment by AustinJColaizzi** [comment]
Is your app being hosted in Azure? My app was under another name in the new portal and took me a while to find it. It was 'Web-app.....'.

 On the old portal it is here:

![image](https://cloud.githubusercontent.com/assets/14980642/19495772/0384a5ea-9542-11e6-8fe9-50b5f64ddb93.png)

and then click this:

![image](https://cloud.githubusercontent.com/assets/14980642/19495794/209c4976-9542-11e6-8b6a-c7865220503c.png).
