### ISSUE TITLE
Issue with API hosted in Azure as App Service

### ISSUE THREAD

**Issue by AustinJColaizzi** [Azure-Samples/active-directory-dotnet-daemon#14]
First off, thank you for the great article and very easy instructions. I got your example to run when registered under my Active Directory in my subscription. 

I then attempted the same exercise and steps with a API we developed that is being hosted in Azure being called by a Daemon/Client app. It is successfully passing a token in the header of the request but it does not authorize. Has anyone hosted their API in Azure and had to do anything in the App.config file or a configuration in the Azure Portal? My suspicion is that it is in Azure as it manually registers the App when you deploy from Visual Studio.

**Comment by dotsad** [comment]
Problem is here:
Find the app key todo:TodoListResourceId and replace the value with the App ID URI of the TodoListService.
It is incorrect, instead of "App ID URI" you should add "App ID" of the TodoListService

**Comment by jmprieur** [comment]
Fixed.
