### ISSUE TITLE
Why ClaimScope Always Getting Null ?

### ISSUE THREAD

**Issue by bhaumikce25** [Azure-Samples/active-directory-dotnet-daemon#15]
Hello My Friend,

We are facing issue in below statement, Could you please help me.

**Claim scopeClaim = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/scope");**

by using above statement we always getting **scopeClaim** 'null'.
for the use of above statement any special kind of permission need to apply in Azure AD Account ?
If needed any kind of permission there then please specify.

Reply me ASAP.

Best Regards,
BhauMik Kanjiya

**Comment by jmprieur** [comment]
Updated the readme and the code. The scope is no longer null.
