### ISSUE TITLE
Group Claim

### ISSUE THREAD

**Issue by TaiAivaras** [Azure-Samples/active-directory-dotnet-daemon#19]
Hi,

Not sure if i'm doing something wrong, but when using this sample and UserPasswordCredential i can't find a way to add a Group claim to the access token. I updated manifest file to read "groupMembershipClaims": "All". Is there something else i should be doing add the group claim?

Thanks

**Comment by kalyankrishna1** [comment]
Please carefully go through the steps again as laid out in the article "https://www.red-gate.com/simple-talk/cloud/security-and-compliance/azure-active-directory-part-4-group-claims/". Double check that the user's account in Azure AD has group memberships. If you still don't see them, contact support and provide them your tenantId and appId,
