### ISSUE TITLE
Issue in 'How to run this sample' instructions

### ISSUE THREAD

**Issue by MaxBarraclough** [Azure-Samples/active-directory-dotnet-daemon#20]
From https://github.com/Azure-Samples/active-directory-dotnet-daemon#register-the-client-app-todolistdaemon

> Enter a friendly name for the application, for example 'TodoListDaemon' and select 'Web app / API' as the Application Type.
>
> Even if this is a desktop application, this is a confidential client application hence the Application Type
>
> For the Redirect URI, enter https://<your_tenant_name>/TodoListDaemon, replacing <your_tenant_name> with the name of your Azure AD tenant.

Azure Portal only shows 'Redirect URI' for a 'Native' type of application. If the 'Web app / API' type is selected, it shows 'Sign-on URL'.

**Comment by JandosKh** [comment]
I stuck on the same point. Moreover, I've noticed that, when I create native app, then I cannot delete the app. [This](https://stackoverflow.com/questions/47081928/i-cant-delete-a-native-app-registration-in-azure-ad-portal) helped me to delete the app; I had to edit the app's manifest to set "availableToOtherTenants" to false. I need to run this sample and learn as quickly as possible. Waiting for someone fixing the guidance on how to run this sample.

**Comment by jmprieur** [comment]
@MaxBarraclough thanks again this is fixed
@JandosKh : I fixed the guidance, but I don't understand why you are stuck, given that MaxBarraclough  wrote the actual new label for the field. What else is blocking you?

**Comment by jmprieur** [comment]
@JandosKh : also did you have a look at the app creation scripts?

**Comment by JandosKh** [comment]
@jmprieur thank you. I'm new to Azure. I thought that this was not just label issue.
