### ISSUE TITLE
Project doesn't build from CLI, builds from VS, but Intellisense doesn't believe it (Microsoft.IdentityModel namespace issue)

### ISSUE THREAD

**Issue by lioobayoyo** [Azure-Samples/active-directory-dotnet-daemon#23]
I installed .NET Core 2.1.402, updated my Visual Studio 2017 Professional to 15.8.5 and cloned the repo as per the README.

The application builds successfully from Visual Studio .

However, everything related to Microsoft.IdentityModel is underlined by Intellisense, despite some restarts. (see screenshot)

![image](https://user-images.githubusercontent.com/1547293/45882833-a29e2600-bdaf-11e8-90bd-c981a7710b6f.png)

I also tried to do `dotnet restore` in case it was some external package issue, but apparently no NuGet package are needed here.

It's a bit problematic to work correctly with a tool believing you are not using correct code.

I digged and tried to use `dotnet build` instead, and it seems I get a related error : 

![image](https://user-images.githubusercontent.com/1547293/45882996-1e986e00-bdb0-11e8-9dcd-165e09f2c032.png)

(sorry for the French in the screenshot, but basically a targeted project was not at all installed in the indicated directory in .NET SDK...)

What could be the cause / fix for this ?

**Comment by kalyankrishna1** [comment]
Seems to me like an issue in your VS.NET installation. Try these steps
1. Clean solution. close and delete bin and obj folders and any .user files and reopen.
2. remove and add Nuget packages that complain
3. Last try repairing vs.net

**Comment by jmprieur** [comment]
I think it's a VS issue. you might want to delete your .suo?

**Comment by jmprieur** [comment]
also @lioobayoyo : did you try to move the source folder closer to the root of your hard disk (long path issue?)

**Comment by lioobayoyo** [comment]
Actually, this looks like an issue of understanding from myself. the project is .NET 4.5, not .NET Core 2.1, right ?

**Comment by jmprieur** [comment]
This should now be fixed with VS 2017.8.8
