### ISSUE TITLE
Where is the "require user assignments" mentioned in the setup step 8 [optional]

### ISSUE THREAD

**Issue by lioobayoyo** [Azure-Samples/active-directory-dotnet-daemon#24]
I can't find any option with this name in my Azure AD Portal .

![image](https://user-images.githubusercontent.com/1547293/45884022-ffe7a680-bdb2-11e8-92a8-a56fe780b285.png)

**Comment by kalyankrishna1** [comment]
Search for your app in the "Enterprise applications" blade. Its available there.
