### ISSUE TITLE
Broken links in the Instructions

### ISSUE THREAD

**Issue by MohamedSahbi** [Azure-Samples/active-directory-dotnet-daemon#26]
The [link ](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/active-directory-applications-guiding-developers-requiring-user-assignment.md) for setting  "User assignment required" is broken.  You will find it on the 8th step [https://github.com/Azure-Samples/active-directory-dotnet-daemon#register-the-service-app-todolistservice-web-api](url)

Same thing for GitHub issues (section: Community Help and Support) and CONTRIBUTING.MD (section Contributing)  in Azure Code Samples  ([here](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-daemon/))

**Comment by jmprieur** [comment]
Thanks for reporting @MohamedSahbi : this is now fixed
