### ISSUE TITLE
Tenant Name vs id

### ISSUE THREAD

**Issue by IainStevenson** [Azure-Samples/active-directory-dotnet-daemon#34]
The instructions stated using the Tenant Name as ida:Tenant in the two config files.

"Find the app key ida:Tenant and replace the existing value with your Azure AD tenant name."

I found that I had to use the Tenant ID value in these two configuration elements for it to work.

**Comment by jmprieur** [comment]
You are right, Tenant can be the tenant ID or the domain name associated with your tenant.
