### ISSUE TITLE
missing check on claim roles 

### ISSUE THREAD

**Issue by myrocode** [Azure-Samples/active-directory-dotnet-daemon#35]
Hello,
the service application (TodoListService) in StartUp Class is checking  only the aud claim, which is not enough. Any Client App Registration in the  same  tenant can receive a valid bearer token with the Server's audience.
As the authorization security is implemented by creating a specific role ( **access_as_application**), the server shall  check also check that  the  claim role **access_as_application**,  has been granted to the client app registration

Or am I missing  something  here?

```
  public partial class Startup
    {
        // For more information on configuring authentication, please visit http://go.microsoft.com/fwlink/?LinkId=301864
        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidAudience = ConfigurationManager.AppSettings["ida:Audience"]
                    }
                });
        }
    }
```

**Comment by jmprieur** [comment]
@myrocode : you are right. It's on my list.

**Comment by jmprieur** [comment]
@myrocode : I've provided a PR (#36)
Thanks again for the heads-up.

**Comment by jmprieur** [comment]
fixed.
