### ISSUE TITLE
Cannot complete manual steps at end.  Error: AADSTS650056

### ISSUE THREAD

**Issue by AlphaCreative** [Azure-Samples/active-directory-dotnet-daemon#38]
At the end of the Configure script it asks you to navigate to the todoList_web_daemon_v1 API Permissions and to click on "Grant admin consent for (your tenant)."

I try that but get the following error:

> Request Id: 26f0629a-b0f4-496e-9d64-79d1fbf25300 
Correlation Id: 09bf39ee-14e0-452a-8c4d-2459f1fba730 
Timestamp: 2019-06-06T14:48:29Z 
Message: AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: <my app id here>

**Comment by jmprieur** [comment]
@AlphaCreative : do you see the app roles in the manifest?

**Comment by AlphaCreative** [comment]
The manifest for "todoListService_web_daemon_v1" shows "access_as_application" in it's app roles array but "todoList_web_daemon_v1" has an empty array for app roles.

**Comment by AlphaCreative** [comment]
OK, I have more information.  I originally was logged in with an account that was setup as a "Limited Administrator".  I changed it to a "Global Administrator" and it worked.  I have another issue though that I'm going to enter where a "Global Administrator" that is of account type "Guest" cannot run the scripts in the sample at all.

**Comment by jmprieur** [comment]
You are right @AlphaCreative that for this sample (all the samples involving daemon apps / client credentials), you need to be a global tenant admin. 

Do you think we need to be more explicit? we have written it in https://github.com/Azure-Samples/active-directory-dotnet-daemon#how-to-run-this-sample ?

**Comment by AlphaCreative** [comment]
I think the updated readme is good.  As for the other issue I mentioned.  It was a Microsoft Account and as the readme says, that won't work.  I think this issue can be closed at this point.
