### ISSUE TITLE
Can you clarify a step in the README.md?

### ISSUE THREAD

**Issue by AlphaCreative** [Azure-Samples/active-directory-dotnet-daemon#39]
Under the section "## How to deploy this sample to Azure" there is a subsection titled "### Update the Active Directory tenant application registration for `TodoListService`" at line 222.  It states: 

> 1. Navigate to the [Azure portal](https://portal.azure.com).
> 2. On the top bar, click on your account and under the **Directory** list, choose the Active Directory tenant containing the `TodoListService` application.
> 3. On the applications tab, select the `TodoListService` application.
> 4. From the Settings -> Reply URLs menu, update the Sign-On URL, and Reply URL fields to the address of your service, for example [https://TodoListService-contoso.azurewebsites.net](https://TodoListService-contoso.azurewebsites.net). Save the configuration.

By "applications tab" in step 3 do you mean "Enterprise Applications" or "App Registrations" or some other section?  If I look for "Sign-On URL" or "Reply URL" under either of those sections, I can't find them. The only thing I could find that was similar was "replyUrlsWithType" and "signInUrl" under the App Registrations/Manifest section.

**Comment by TiagoBrenck** [comment]
@AlphaCreative I am sorry for the confusion. 
So, this "Reply Url" will be under "App registrations", then on the main window find the text "Redirect URIs" and click on the link right beside it. It will lead you to the screen where you can add/edit the redirect Urls. 
In this particular sample, we don`t have Sign-On url, so please ignore this step.

The Manifest file is a JSON representation of all the configs for that application. See it as a "web.config" sort of file. Developers that are more familiarized with Portal Azure, change the configurations directly from the Manifest, however we only recommend it if you really know what you are doing. You can read more about Manifest here: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest

**Comment by AlphaCreative** [comment]
Thanks.  That answers that question however after following that final step and configuring the "TodoListDaemon" to point to the azure service, it fails when posting the Todo on line 82 of Program.cs.  If I run "TodoListDaemon" but have it configured to point to the local "TodoListService" it works fine.

Here is the error I'm getting: 

>  System.AggregateException
>   HResult=0x80131500
>   Message=One or more errors occurred.
>   Source=mscorlib
>   StackTrace:
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at TodoListDaemon.Program.Main(String[] args) in C:\temp\active-directory-dotnet-daemon-master\TodoListDaemon\Program.cs:line 82
> 
> Inner Exception 1:
> HttpRequestException: An error occurred while sending the request.
> 
> Inner Exception 2:
> WebException: The underlying connection was closed: An unexpected error occurred on a send.
> 
> Inner Exception 3:
> IOException: Authentication failed because the remote party has closed the transport stream.

**Comment by TiagoBrenck** [comment]
@AlphaCreative I have proposed a PR:https://github.com/Azure-Samples/active-directory-dotnet-daemon/pull/40 with the fix.
Feel free to change your code and try again. It is just one line of code.

**Comment by AlphaCreative** [comment]
I read the comments in the PR and upgraded to dontnet 4.7.  That resolved the issue for me.  Thanks!
