### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by kellyrford** [Azure-Samples/active-directory-dotnet-daemon#41]
Followed the example to the letter and the above error message was returned for all calls to httpClient.PostAsync.

Finally resolved the problem.  Need to add this line above the call:

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by jmprieur** [comment]
Hi @kellyrford : this is not the right fix. See https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls
What we need to do is change the project to be a .NET Framework to be 4.7+
cc: @kalyankrishna1 @TiagoBrenck

**Comment by TiagoBrenck** [comment]
@jmprieur this sample is already .NET 4.7.2. Check this PR: https://github.com/Azure-Samples/active-directory-dotnet-daemon/commit/14f913671e6d79f2078d275945144d8236d221f4

**Comment by jmprieur** [comment]
@kellyrford : did you change the version of the .NET framework in the project? 
cc: @TiagoBrenck

**Comment by kellyrford** [comment]
I did not change the .NET framework of the project. It is 4.7.2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TiagoBrenck** [comment]
@kellyrford I believe you are having this problem when you deploy to Azure right?
On the step to create the web app resource, Azure AD askes you to select a **Runtime stack**. What option did you choose?

**Comment by TiagoBrenck** [comment]
@kellyrford should I close this issue?

**Comment by kellyrford** [comment]
Yes. It is fine to close it.  Not sure why it was not detecting the right tls version but without declaring it, the azure site would reject the connection.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
