### ISSUE TITLE
Is new sample link pointing to an incorrect sample?

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure-Samples/active-directory-dotnet-daemon#42]
This sample is for a damemon calling a Web API, however the new sample link below is pointing to a sample of damemon calling Microsoft Graph API. Is there a new sample for a daemon calling an Web API?

https://github.com/azure-samples/ms-identity-dotnetcore-daemon-console.

Regards
Rahul

**Comment by jmprieur** [comment]
Hello @rahulvmarathe 
The .NET core daemon tutorial is now a multi-step tutorial. The second steps shows the daemon calling a Web API:
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/msal3x/2-Call-OwnApi
